### ISSUE TITLE
Version FAR_0_7_0_3 (CPY)  crashes when trying to disabled the default OSD.

### ISSUE THREAD

**Issue by walterLTrapa** [marcussacana/FAR#12]
Firstly, I created this as a new issue because all the changes related to dinput8 in the 7.0 version

Control + Shift +  Backspace makes the game crash
Bask + Start (Gamepad) makes the came crash.
Control + Shift + O Works.

It is ok not to used. Actually I don't know what it is in there.

I have x96dbg so if you tell me what should I look for I might be able to help:

So far in x64dbg I have a EXCEPTION_ACCESS_VIOLATION steam_64api

000000003B40D72D | 00 00                    | add byte ptr ds:[rax],al                |
000000003B40D72F | 00 70 1C                 | add byte ptr ds:[rax+1C],dh             |
000000003B40D732 | 40 3B 00                 | cmp eax,dword ptr ds:[rax]              |
000000003B40D735 | 00 00                    | add byte ptr ds:[rax],al                |
000000003B40D737 | 00 80 1C 40 3B 00        | add byte ptr ds:[rax+3B401C],al         |
000000003B40D73D | 00 00                    | add byte ptr ds:[rax],al                |
000000003B40D73F | 00 60 D7                 | add byte ptr ds:[rax-29],ah             |
000000003B40D742 | 40 3B 00                 | cmp eax,dword ptr ds:[rax]              |
000000003B40D745 | 00 00                    | add byte ptr ds:[rax],al                |
000000003B40D747 | 00 40 D7                 | add byte ptr ds:[rax-29],al             |
000000003B40D74A | 40 3B 00                 | cmp eax,dword ptr ds:[rax]              |
000000003B40D74D | 00 00                    | add byte ptr ds:[rax],al                |
000000003B40D74F | 00 00                    | add byte ptr ds:[rax],al                |
000000003B40D751 | 00 00                    | add byte ptr ds:[rax],al                |
000000003B40D753 | 00 00                    | add byte ptr ds:[rax],al                |
000000003B40D755 | 00 00                    | add byte ptr ds:[rax],al                |
000000003B40D757 | 00 00                    | add byte ptr ds:[rax],al                |

**Comment by DStrifer** [comment]
1. manual FAR.ini (GlobalIlluminationWorkgroups=32)  makes no impact on the game as it does with baldman v3. But who cares! With this mod my old SAVES are back! i`m so fkn happy!))))

**Comment by shinobuowo** [comment]
same problem here (CPY) :(

Control + Shift + Backspace makes the game crash
Back + Start (xbox 360) makes the game crash

**edit:**

**nvm CPY is pure crap I just use the baldman v3 crack + FAR_0_7_0_3.7z by marcussacana and it worked perfectly**

**Comment by marcussacana** [comment]
I think is better say now, cpy isn´t compatible.
I don't touched in the crack to know the crash reason, i think i don't need try fix, why?, why we can use the baldman v3.
And this is a fucking denuvo game, i think if i try debug the cpy crack to know the reason is just waste of effort, i'm not a pro cracker, my work with this mod is just like a help to the community, because someone just like help your own community type, sorry guys, but just use the baldman v3, works fine...
I hope if the steampunks someday create a keygen to this game too (I Know, we already have 2 cracks), and everyone can play with a stable way with the mod

**Comment by walterLTrapa** [comment]
Sure, I will give it a try anyway :)

**Comment by walterLTrapa** [comment]
I lost my game saves with the other crack, but after some edittings of the GameSave files it works agains.
FAR works as well.
