### ISSUE TITLE
Baldman V3 also crash

### ISSUE THREAD

**Issue by kalonkboy** [marcussacana/FAR#13]
Hello, i already using baldman v3 crack from the start but it's seems when i messed up the setting in game or just simply press start the game crashed. Any tips?

**Comment by marcussacana** [comment]
You have any external program that try hook the game?
if yes try disable it...

**Comment by kalonkboy** [comment]
My baldman crack come with SSELauncher to open the game. is it count as external program? if so how can i open the game without it?

**Comment by marcussacana** [comment]
Nop, i'm saying about programs who inject in the game, like the steam overlay...  or something that show the gpu/cpu status

**Comment by kalonkboy** [comment]
nope, just sseLauncher and nothing else.

**Comment by marcussacana** [comment]
What version of the mod are you using?
Man, i really can't help much, i don't know what are ocurring, maybe if you run in the compatibility mode? , if you really want use it, maybe reinstall the windows can help
Any try use the Nst, Old, Outdated builds from here: https://github.com/marcussacana/FAR/releases/tag/far_057

**Comment by kalonkboy** [comment]
im using your latest version. Oh btw im using Nier automata ISO for installing from CPY release, but crack it with Baldman V3 and im using win 7 ultimate x64 with custom DPI of 150%. Maybe that info can help? if there is no other way i will try the old version first

**Comment by kalonkboy** [comment]
I managed to play without crash using FAR MOD 0.6.0.1 patch. i got it from yout***. I don't know if it's one of your patch or not. Thx for your  help
