### ISSUE TITLE
can't install FAR

### ISSUE THREAD

**Issue by sushiyogurt** [marcussacana/FAR#14]
The install option in the SKIM is greyed out, at the bottom saying the game is not installed. 
If I extract from the FAR zip file (not sure which version I should use here) the game run as normal without the yellow text, pressing ctrl+shift+backspace doesnt bring the FAR menu either. but after playing for a while, I'll get the MGS sound and the game crash

**Comment by marcussacana** [comment]
The SKIM install the original mod, not the cracked.
https://github.com/marcussacana/FAR/releases/download/far_070/FAR_0_7_0_14.7z
this is the lastest version.
Try SELECT + START from the joystick or CTRL + ALT + SHIFT + BACKSPACE

**Comment by sushiyogurt** [comment]
thnx for your attention. I got to change the resolution to properly fit my monitor, so i guess that's something... still can't show the FAR menu tho. from what i heard there's some settings I should change in there that'll make the game run smoother and more stable. as of right now, I still get the occasional crashes with the MGS alert sound

**Comment by marcussacana** [comment]
If you hear the MGS alert the FAR is already installed and running, you can manually setup at dinput8.ini

**Comment by sushiyogurt** [comment]
sorry, 1 more thing. can you show me where do i edit in dinput8 to change global illumiation quality, under lighting?

**Comment by marcussacana** [comment]
Edit at FAR.ini
![https://a.pomf.cat/oxkuvb.png](https://a.pomf.cat/oxkuvb.png)
