### ISSUE TITLE
FAR 0.7.0.22 Final

### ISSUE THREAD

**Issue by nbmrjuhneibkr** [marcussacana/FAR#16]
FAR 0.7.0.22 is out, and it should be the final release. Are you going to update your version?

**Comment by marcussacana** [comment]
I lost my copy of the nier and don't have a joystick now... maybe at the end of january...

**Comment by KanekiK3n** [comment]
It got updated again, maybe you were already aware of it but just to let you know and also good job it took me some time to find this but it was worth it in the end.

**Comment by wolfxana** [comment]
i would really like to help , i really want to demo Nier with the latest far

**Comment by marcussacana** [comment]
Yeah, it's time to start reinstall the game 
but... huh...
![https://a.safe.moe/m3v8q.png](https://a.safe.moe/m3v8q.png)

**Comment by marcussacana** [comment]
I will travel for 7 days, after return I will crack it, frankly it would be good for someone to come in 7 days and charge me for the update may be that I forget.

**Comment by KanekiK3n** [comment]
*Pling* (notification)
Hi, 7 days have past

**Comment by marcussacana** [comment]
Just in time, have 2 hours i'm back... Okay, let's work!

**Comment by marcussacana** [comment]
I haven't started the game since i lost my save and I need a time to can walk in the map after the new game...
But if have any detection of the crack just create other issue, for now, looks all right here...
![https://vgy.me/diRWIS.png](https://vgy.me/diRWIS.png)
