### ISSUE TITLE
NieR doesn't start

### ISSUE THREAD

**Issue by KanekiK3n** [marcussacana/FAR#19]
After copying and replacing with the new files NieR opens and then Immediately exits.

**Comment by marcussacana** [comment]
is the baldman version with SSE or other api?

**Comment by KanekiK3n** [comment]
It's the legit game but with creamAPI for the dlc

**Comment by KanekiK3n** [comment]
01/29/2018 20:23:28.592: -----------------------------------------------------------
01/29/2018 20:23:28.592: [! Except !] 	<< EXCEPTION_ACCESS_VIOLATION >>
01/29/2018 20:23:28.592: -----------------------------------------------------------
01/29/2018 20:23:28.592: [ FaultMod ]  # File.....: 'D:\Steam\steamapps\common\NieRAutomata\steam_api64.dll'
01/29/2018 20:23:28.592: [ FaultMod ]  * RIP Addr.: steam_api64.dll+00000000000392FCh
01/29/2018 20:23:28.592: [StackFrame] <-> Rip=7ffac10992fch, Rsp=00000014ed68h, Rbp=00000014f110h
01/29/2018 20:23:28.592: [StackFrame] >-< Rsi=000000000001h, Rdi=000047aaa360h
01/29/2018 20:23:28.592: [  GP Reg  ]       rax:     0x7ffac1096720
01/29/2018 20:23:28.592: [  GP Reg  ]       rbx:     0x00000014ed98
01/29/2018 20:23:28.592: [  GP Reg  ]       rcx:     0x00000fb19b40
01/29/2018 20:23:28.592: [  GP Reg  ]       rdx:     0x000047aaa360
01/29/2018 20:23:28.592: [  GP Reg  ]        r8:     0x0000001a1a40       r9:      0x000000008000
01/29/2018 20:23:28.592: [  GP Reg  ]       r10:     0x000047af7d50      r11:      0x000047aff380
01/29/2018 20:23:28.592: [  GP Reg  ]       r12:     0x000000000000      r13:      0x000000000000
01/29/2018 20:23:28.592: [  GP Reg  ]       r14:     0x000000000000      r15:      0x000000000001
01/29/2018 20:23:28.592: [ GP Flags ]       EFlags:  0x00010206
01/29/2018 20:23:28.592: -----------------------------------------------------------
01/29/2018 20:23:28.593: [--(Name)--] [!] {         steam_api64.dll}                                            VR_GetGenericInterface
01/29/2018 20:23:28.593: [--(Name)--] [!] {         steam_api64.dll}                                            VR_GetGenericInterface
01/29/2018 20:23:28.595: [-(Source)-] [!] {             dinput8.dll}                                             SK_Steam_PiratesAhoy  <c:\users\andon\source\repos\specialk\src\steam_api.cpp:4301> 
01/29/2018 20:23:28.605: -----------------------------------------------------------
01/29/2018 20:23:28.606: -----------------------------------------------------------
01/29/2018 20:23:28.606: [! Except !] 	<< EXCEPTION_ACCESS_VIOLATION >>
01/29/2018 20:23:28.606: -----------------------------------------------------------
01/29/2018 20:23:28.606: [ FaultMod ]  # File.....: 'D:\Steam\steamapps\common\NieRAutomata\steam_api64.dll'
01/29/2018 20:23:28.606: [ FaultMod ]  * RIP Addr.: steam_api64.dll+00000000000392FCh
01/29/2018 20:23:28.606: [StackFrame] <-> Rip=7ffac10992fch, Rsp=00000014ed68h, Rbp=00000014f110h
01/29/2018 20:23:28.606: [StackFrame] >-< Rsi=000000000001h, Rdi=000047aaa360h
01/29/2018 20:23:28.606: [  GP Reg  ]       rax:     0x7ffac1096720
01/29/2018 20:23:28.606: [  GP Reg  ]       rbx:     0x00000014ed98
01/29/2018 20:23:28.606: [  GP Reg  ]       rcx:     0x00000fb19b40
01/29/2018 20:23:28.606: [  GP Reg  ]       rdx:     0x000047aaa360
01/29/2018 20:23:28.606: [  GP Reg  ]        r8:     0x0000001a1a40       r9:      0x000000008000
01/29/2018 20:23:28.606: [  GP Reg  ]       r10:     0x000047af7d50      r11:      0x000047aff380
01/29/2018 20:23:28.606: [  GP Reg  ]       r12:     0x000000000000      r13:      0x000000000000
01/29/2018 20:23:28.606: [  GP Reg  ]       r14:     0x000000000000      r15:      0x000000000001
01/29/2018 20:23:28.606: [ GP Flags ]       EFlags:  0x00010206
01/29/2018 20:23:28.606: -----------------------------------------------------------
01/29/2018 20:23:28.606: [--(Name)--] [!] {         steam_api64.dll}                                            VR_GetGenericInterface
01/29/2018 20:23:28.607: [--(Name)--] [!] {         steam_api64.dll}                                            VR_GetGenericInterface
01/29/2018 20:23:28.607: [--(Name)--] [!] {             dinput8.dll}                                        SK_SteamAPI_TakeScreenshot
01/29/2018 20:23:28.613: -----------------------------------------------------------
01/29/2018 20:23:28.613: -----------------------------------------------------------
01/29/2018 20:23:28.613: [! Except !] 	<< EXCEPTION_ACCESS_VIOLATION >>
01/29/2018 20:23:28.613: -----------------------------------------------------------
01/29/2018 20:23:28.613: [ FaultMod ]  # File.....: 'D:\Steam\steamapps\common\NieRAutomata\steam_api64.dll'
01/29/2018 20:23:28.613: [ FaultMod ]  * RIP Addr.: steam_api64.dll+00000000000392FCh
01/29/2018 20:23:28.613: [StackFrame] <-> Rip=7ffac10992fch, Rsp=00000014ed68h, Rbp=00000014f110h
01/29/2018 20:23:28.613: [StackFrame] >-< Rsi=000000000001h, Rdi=000047aaa360h
01/29/2018 20:23:28.613: [  GP Reg  ]       rax:     0x7ffac1096720
01/29/2018 20:23:28.613: [  GP Reg  ]       rbx:     0x00000014ed98
01/29/2018 20:23:28.613: [  GP Reg  ]       rcx:     0x00000fb19b40
01/29/2018 20:23:28.613: [  GP Reg  ]       rdx:     0x000047aaa360
01/29/2018 20:23:28.613: [  GP Reg  ]        r8:     0x0000001a1a40       r9:      0x000000008000
01/29/2018 20:23:28.613: [  GP Reg  ]       r10:     0x000047af7d50      r11:      0x000047aff380
01/29/2018 20:23:28.613: [  GP Reg  ]       r12:     0x000000000000      r13:      0x000000000000
01/29/2018 20:23:28.613: [  GP Reg  ]       r14:     0x000000000000      r15:      0x000000000001
01/29/2018 20:23:28.613: [ GP Flags ]       EFlags:  0x00010206
01/29/2018 20:23:28.613: -----------------------------------------------------------
01/29/2018 20:23:28.613: [--(Name)--] [!] {         steam_api64.dll}                                            VR_GetGenericInterface
01/29/2018 20:23:28.614: [--(Name)--] [!] {         steam_api64.dll}                                            VR_GetGenericInterface
01/29/2018 20:23:28.614: [--(Name)--] [!] {             dinput8.dll}                                        SK_SteamAPI_TakeScreenshot
01/29/2018 20:23:28.620: -----------------------------------------------------------

**Comment by marcussacana** [comment]
To prevent takedown of this repo, tell me your email, i will send a soluction to you

**Comment by KanekiK3n** [comment]
i.b.berre@hotmail.com   Thanks!!
