### ISSUE TITLE
Outdated address

### ISSUE THREAD

**Issue by nbmrjuhneibkr** [marcussacana/FAR#2]
I'm not an expert in this, but I'm pretty sure that the cracked binary is not outdated. As far as i know, there were only two versions of NierAutomata.exe, and the binary comparison between the old, new and cracked file shows that the cracked file is a modified version of the current executable.
So, by stating that the cracked version is outdated, Kaldaien is being either deceptive or just plain wrong.

**Comment by marcussacana** [comment]
Nop, you understanded wrong my friend.
This isn't the outdated version of the mod, This is the newest version with memory address of the old version of the mod.

This is a try to stop the crash of the mod.

This time i don't patch the PirateAHoy function, i patch the code to delete the cpy crack and the pirate message.

**Comment by nbmrjuhneibkr** [comment]
It seems like you misunderstood me too. I know this is the new version of the mod with the old memory address. But the old memory address should be used with the old version of the game. And the cracked NierAutomata.exe is from the current build of the game, not the old one.

"This time i don't patch the PirateAHoy function" - why? I thought that function controls all of the anti-piracy measures in the mod.

**Comment by marcussacana** [comment]
Yeah, but if i patch who use the function he have the same result, this is just a try to stop the MSG Sound.

I see, the crack use the lastest version of the game... I don't check this before release, thx to say.

You know when the new executable has been released? (in the steam)

**Comment by nbmrjuhneibkr** [comment]
https://steamdb.info/app/524220/depots/ - last update was 16 days ago.

As far as I know, the MGS alarm sound doesn't mean that FAR has caused the crash - it just indicates that the game has crashed. People are experiencing crashes on some systems with or without FAR, and this is most likely caused by the cracked executable. Nothing can be done about this unless someone makes a better crack.

**Comment by marcussacana** [comment]
Yeah, you are right, but i need consider the words of the owner of this mod...
I Don't like know my work is crashing the game from some peoples. if he is right i need try something.

I can say, the crash isn't a fault of the steam emu, is a fault of the executable.

And yeah, looks the new executable don't work with the oudated address.
![https://u.nya.is/krcges.png](https://u.nya.is/krcges.png)

**Comment by marcussacana** [comment]
i push the updated address versoin as Testing Build of the auto-update, 
Testing just because is a new crack method.

Thanks for this report man.
And, Hail CPY... i hope a fix from the group maybe a day.
