### ISSUE TITLE
Internal error 0x0D: Interface not found: SteamUser023!

### ISSUE THREAD

**Issue by ghost** [marcussacana/FAR#20]
That error message pops up when I try to start NieR

**Comment by marcussacana** [comment]
What Steam API/Crack are you using?

**Comment by ghost** [comment]
I'm using FitGirl which says it uses Baldman V3

**Comment by marcussacana** [comment]
I will do a look tomorrow, here is 2:40 AM

**Comment by ghost** [comment]
Ok cool!

**Comment by pgiao** [comment]
Same here, both with Baldman v3 exe and CPY fix, found a "Custom dinput8.dll Detached" in dinput8.log don't know if related or not
![image](https://user-images.githubusercontent.com/31972527/35560092-b1981b86-05ac-11e8-8473-f99fe9b47693.png)

**Comment by wolfxana** [comment]
i already posted issue and i closed it , the solution go to *.ini files and look for [Steam.Log] 
Silent = false; make it true 👍

**Comment by marcussacana** [comment]
Try the hint of the @wolfxana for now, someone can upload to me the baldman v3 with SSE? 
give the link to my email: ddtank.marcus@gmail.com
I Only found versions with other api

**Comment by pgiao** [comment]
Sent, btw tried with Silent = true and it seems to work (it starts at least). thx

**Comment by marcussacana** [comment]
Bald v3 + SSE, Received, i will do a look into the problem in 3 days....
