### ISSUE TITLE
question about the last version 7.0.23 

### ISSUE THREAD

**Issue by Kojikun1** [marcussacana/FAR#21]
thanks for you work i have question this version 7.0.23 works on cpy crack ?

**Comment by marcussacana** [comment]
I think nop, this my last 7.0.23 is the wrost cracked version published here, since others don't works i think this will not work.
I will update it after... maybe... but i think will not work with cpy crack.

**Comment by Gerchan** [comment]
Where can I download 7.0.23 version? I must be blind...

**Comment by Kojikun1** [comment]
A question what version do you think is the best  cracked version published here.

**Comment by marcussacana** [comment]
for now, maybe the FAR_0_7_0_9.7z

**Comment by Kojikun1** [comment]
thankyou

**Comment by akiirui** [comment]
for CPY version.
Edit default_dinput8.ini and dinput8.ini, Find 
```
[Steam.Log]
Silent=false
```
change `false` to `true` and FAR working fine

**Comment by Kojikun1** [comment]
@MayKiller Thankyou
