### ISSUE TITLE
Version 0.7.0.23 Error (Internal Error 0x0D: Interface not found: SteamUser023!)

### ISSUE THREAD

**Issue by SirHarleyquinn** [marcussacana/FAR#22]
I'm having this error with the latest version, but with the previous version the game starts normally, am I doing something wrong?
![asd](https://user-images.githubusercontent.com/36176275/35834848-aa1db822-0abe-11e8-9052-77daab709a15.png)

**Comment by marcussacana** [comment]
You do nothing wrong, I forget to patch a new change in the anti-piracy algorithm of that kid, 
I Will update soon... I'm just without time now, maybe in one week

**Comment by SirHarleyquinn** [comment]
No problem man, i'll use your x.x.x.14 for now.
