### ISSUE TITLE
é só descompactar na pasta do nier?

### ISSUE THREAD

**Issue by K9998f** [marcussacana/FAR#4]
hein marcus, é que nem o do kaldaien mesmo, é só descompactar lá dentro?

**Comment by marcussacana** [comment]
Exato, basta descompactar, qualquer problema dele detectando o crack basta me avisar.

**Comment by K9998f** [comment]
Então, exatamente... Quando eu abro, ele me dá duas mensagens dizendo que o "steamapi64.dll" é um arquivo malicioso e que eu deveria deletá-lo, primeiro uma, depois outra. Ai toda vez que eu for jogar tenho que ficar fechando as duas, o que é um incômodo, porque eu jogo longe do teclado e do mouse. O que eu faço?

**Comment by marcussacana** [comment]
Isso é o windows defender ou algum antivírus então...
Ao meu ver os antivírus devem receber uma propina pra acusar verdadeiros cracks de malware...
Infelizmente só desligando ou adicionando a pasta do nier na lista de exceções.

**Comment by K9998f** [comment]
Vou tentar aqui... Mais tarde, edito

edit: Cara, não deu em nada. Desabilitei o antivirus, adicionei a pasta como exceção... Nada surtiu efeito.

Tenho a impressão de que é o FAR que tá causando isso. Até porque a janela de mensagem sobre o "steamapi64.dll" ser malicioso, está tendo como origem o executável do jogo.

Segue o anexo reforçando minha tese:
![sem titulo](https://cloud.githubusercontent.com/assets/27894906/26764529/af50bcaa-493e-11e7-8794-c4d554287857.png)

**Comment by marcussacana** [comment]
eu encotrei! hahaha, aguarde um segundo.

**Comment by marcussacana** [comment]
Isso foi o kidaien mesmo cara... o código está presente no dll mas não executou comigo portanto acabei atualizando sem ver... malz... baixa o FAR 0.6.0 novamente e diga o que rolou.

**Comment by K9998f** [comment]
Agora foi. Tá liso, 100%

bom trabalho e continue assim

**Comment by marcussacana** [comment]
Sem problema, ele fazer isso novamente portanto qualquer problema futuramente basta vir aqui.
Bom jogo, E Viva a Pirataria!

**Comment by marcussacana** [comment]
Amigo dei uma olhada e me parece que isso não é sistema anti-pirataria e uma proteção de verdade, tente baixar o crack do lugar certo... 
https://gitlab.com/Kaldaien/SpecialK/blob/0.8.x/src/diagnostics/compatibility.cpp#L988
