### ISSUE TITLE
0.5.7.4?

### ISSUE THREAD

**Issue by nbmrjuhneibkr** [marcussacana/FAR#5]
https://github.com/Kaldaien/FAR/blob/master/version.ini

0.5.7.4 is the current stable release, but I don't see a patched 0.5.7.4 here. Could you upload it too, please?

**Comment by marcussacana** [comment]
no problem, return in 10m

**Comment by nbmrjuhneibkr** [comment]
Thanks.

**Comment by marcussacana** [comment]
released
