### ISSUE TITLE
No nier Automata section

### ISSUE THREAD

**Issue by Kaktusmann** [marcussacana/FAR#6]
Hey! First of all thanks for doing this, I and I'm sure many other thank you for your work. 
My problem is I don't have that NieR:Automata options section at all like in the screen of the official release (https://steamuserimages-a.akamaihd.net/ugc/781785179826324400/D7067B6027933DC7952389F5EB664A204243E408/)
Mine looks like this: http://i.imgur.com/rwxt2FS.png
Did I do something wrong?
6.0.1 installed

**Comment by marcussacana** [comment]
isn't because the hotkey change?
before we need press CTRL + ALT + BACKSCAPE to open this menu
but now, we need press CTRL + SHIFT + BACKSCAPE to open this menu
or if you have a joystick, press SELECT + START...

if is really a bug, you have any other program that overlay the nier?

**Comment by marcussacana** [comment]
Try launch with this dll:
[FAR 0.6.1 - Nier Only.zip](https://github.com/marcussacana/FAR/files/1059333/FAR.0.6.1.-.Nier.Only.zip)

**Comment by Kaktusmann** [comment]
I fixed it, kinda. 
The problem was I was playing Nier through an ahk script compiled as exe to load and close my scripts automatically 
Far doesn't see I'm playing NieR - reverting my changes and starting the scripts manually works.
