### ISSUE TITLE
nier automata

### ISSUE THREAD

**Issue by Hanzoswitch** [marcussacana/FAR#7]
Hi bro first thx for all the work you are doing for us...
but i have a probelm with nier when i put your FAR mod in it and press (shift+ctrl+backspace) nottting happen.
so can you pls tell me what version do i download and its working with what version of crack i will be much greatful to you my friend...
and thanks agian :)

**Comment by marcussacana** [comment]
First we have sure the mod has been started, 
If exist, delete a directory called logs in the nier directory...
And launch the nier, see if the logs directory has been created again.

Try too press CTRL + SHIFT + O to see if the mod has been started... (if yes you can see yellow letters)

If are you using older version of the mod, the correct hotkey to open the menu is CTRL + ALT + BACKSCAPE

**Comment by Hanzoswitch** [comment]
do i use V3 crack from baldman or V3 codex emu? with your mod

**Comment by marcussacana** [comment]
i don't think this can change anything...

**Comment by Hanzoswitch** [comment]
ok i done what you said and when i press (ctrl+shift+O) notting happen too and the logs file was created and i deleted it and started the game the logs file was created agian.

**Comment by marcussacana** [comment]
zip and upload your log

**Comment by Hanzoswitch** [comment]
dude i don't know why it don't let me upload it..it says
We don’t support that file type. Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP.
*i did zip it*

**Comment by marcussacana** [comment]
http://zippyshare.com

**Comment by Hanzoswitch** [comment]
http://www86.zippyshare.com/v/oTbFo6Ku/file.html
done....sorry man but pls stay with me :)

**Comment by marcussacana** [comment]
what version of the mod are you using?
```
06/08/2017 19:28:00.149: [ Module ]  ( 000007FEE6E30000h + 00901120 )   -:< SteamInternal_CreateInterface                                    >:-   D:\NieR Automata\steam_api64.dll
 ----------------------  [File Ver]    Steam Client API (buildbot_winslave007@WUS)  01.0.1.08
```

By now try download the baldman v3 + SSE, i don,t know why but looks the steam overlay has started with the game.... and use the original steam api, this is my:
[steam_api64.zip](https://github.com/marcussacana/FAR/files/1062273/steam_api64.zip)

and check if in the nier directory exist the file dxgi.ini and FAR.ini...

**Comment by Hanzoswitch** [comment]
![untitled](https://user-images.githubusercontent.com/29280074/26948939-6676a1ae-4c98-11e7-8237-369722732a30.png)
still didn't tried pressing every bottn (ctrl+shift+O)
(ctrl+shift+backspace)
(ctrl+O) and still FAR mod window didn't open :(

**Comment by marcussacana** [comment]
send the log using the SSE plz, and try run with this versoin of the mod: https://github.com/marcussacana/FAR/releases/download/far_057/FAR_Oudated.7z

**Comment by Hanzoswitch** [comment]
http://www60.zippyshare.com/v/Ree1NQ2v/file.html
this is the logs from using SSE
and the far_057 didn't work either.

**Comment by marcussacana** [comment]
looks the nier is connecting with your steam  client
```
06/08/2017 22:16:21.649: [DLL Loader]   ( steam_api64.dll              ) loaded '                  C:\Program Files (x86)\Steam\steamclient64.dll' <LoadLibraryExW> { 'SteamAPI_SetTryCatchCallbacks' }`
```

Close your steam client before launch the nier, and in the DXGI.ini try set this to true
![https://u.nya.is/hvmzgt.png](https://u.nya.is/hvmzgt.png)

and here, try set this to false:
![https://u.nya.is/ewpdsx.png](https://u.nya.is/ewpdsx.png)

Delete the logs, lauch and send again to me.

**Comment by Hanzoswitch** [comment]
http://www20.zippyshare.com/v/APmDo1Vg/file.html
done,,,still won't open
and thanks for helping me man i really appreciate that :+1:

**Comment by marcussacana** [comment]
haha, anyway i´m the creator of this mod, i think i can´t help much....

hmm looks the steam continues injected in the nier... 

By now, i try update to the lastest version, looks you have a problem with the texture cache...

**Comment by Hanzoswitch** [comment]
same thing man i tried everything and notting worked  for me hahahaha guess its just my luck...
anyways thanks for all the help man hope you have a wonderful day :)

**Comment by Hanzoswitch** [comment]
is there any way to lower the global illumination without FAR mod i think it will fix my fps probelm

**Comment by marcussacana** [comment]
try launch the far 0.6.0.3, i release it now...
Hmm the global illumination is originally a code from other modder but i don´t found he code ready to use....

**Comment by Hanzoswitch** [comment]
just tried it with both cracks (codex and baldman)
still can't open FAR mode window...
does FAR working for you if yes can you tell me what version of FAR and what crack are you using so i can copy your settings to mine

**Comment by marcussacana** [comment]
my config:
[NieR Automata.zip](https://github.com/marcussacana/FAR/files/1062730/NieR.Automata.zip)
Version 0.6.0.1

**Comment by Hanzoswitch** [comment]
and what crack are you using?

**Comment by marcussacana** [comment]
to test the baldman v3 + sse

**Comment by Hanzoswitch** [comment]
yup still didn't work i will look for other ways to lower global illumination without FAR mod
but thanks for the help my friend :)

**Comment by marcussacana** [comment]
in last case you can try format your computer?
sorry for don´t help.

**Comment by Hanzoswitch** [comment]
No man don't say that you did help me ALOT so thanks again and wish you best of luck :)
