### ISSUE TITLE
 Getting ReShade to work.

### ISSUE THREAD

**Issue by Dadada224** [marcussacana/FAR#9]
I just can't get reshade to work alongside FAR, no matter what method I try. 
I know it looks like something I should ask to the original developer, but some people told me it's something specific to non-original copies of the game, so I thought I should ask here and hope to get some help.

 Ajuda aê, valeu.

**Comment by marcussacana** [comment]
Bem, tente isso, sendo que os passos que já tiver feito apenas ignore.

Primeiro faça com que essa pasta exista e abra ela:
%userprofile%\Documents\My Mods\SpecialK\PlugIns\ThirtdParty\ReShade\
Pode simplesmente colar isso no prompt de comando:
```batch
mkdir "%userprofile%\Documents\My Mods\SpecialK\PlugIns\ThirtdParty\ReShade\"
explorer "%userprofile%\Documents\My Mods\SpecialK\PlugIns\ThirtdParty\ReShade\"
```
Baixe isso e coloque-o na pasta criada que abriu: https://reshade.me/downloads/ReShade_Setup_3.0.7.exe
Execute-o, Segure "Ctrl" e clique em "Select Game".
Ele irá criar os arquivos na pasta... simplesmente feche.

## Agora o truque
Essa etapa irá forçar o FAR carregar o ReShade, se for problema de incompatibilidade o Nier não irá iniciar.
Abra o dxgi.ini, no final adicione essas linhas
```ini
[Import.ReShade64]
Architecture=x64
Role=ThirdParty
When=PlugIn
Filename=EDITE AQUI\Documents\My Mods\SpecialK\PlugIns\ThirtdParty\ReShade\ReShade64.dll
```
Mude o "EDITE AQUI" para o caminho que leva a sua pasta de documentos, exmplo: `C:\Users\Dadada224\Documents\My Mods\SpecialK\Plugins\ThirtdParty\ReShade\ReShade64.dll`

Tente rodar o NieR, e fique de olho no processo dele pelo gerenciador, se ele fechar é porque o ReShade foi carregado mais algum problema rolou, este foi o meu caso, eu arrumei isso da seguinte forma:

1 - Clique com botão direito sobre o Executável do NieR e vá em "Propriedades"
![https://u.nya.is/kqsdma.png](https://u.nya.is/kqsdma.png)

2 - Vá em "Compatibilidade" e deixe as configurações iguais as minhas:
![https://u.nya.is/lunvbn.png](https://u.nya.is/lunvbn.png)
3 - Clique em "Aplicar" e tente novamente.

>Com isso o nier funcionou com reshade aqui, boa sorte.

**Comment by Dadada224** [comment]
Funcionou a primeira vez que eu abri o jogo, mas agora o reshade não funciona mais. Alguma idéia? 
 E esse foi o método que mais chegou perto de funcionar, só que não funciona de jeito nenhum mais.

**Comment by marcussacana** [comment]
Não faço ideia então cara, tente repetir as etapas.
Se tu tem qualquer programa da MSI ou Razer, tente desabilitar antes de rodar o jogo.

**Comment by Dadada224** [comment]
Ah, resolvi o problema.
 Por mais estranho que pareça, já que a opção de overlay está desligada, o que estava interferindo no funcionamento do ReShade era o Discord, quando eu fecho ele e abro o jogo, o ReShade funciona perfeitamente.
 Muito obrigado pela ajuda.
